version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - ./gradlew build --dry-run --configure-on-demand --daemon
  build:
    commands:
      - ./gradlew clean test cucumber