version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - docker run --rm -v "$PWD":/home/gradle/project -w /home/gradle/project gradle gradle clean test cucumber