version: 0.2

phases:
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/archive-test-artifacts.sh
      - echo "==============================================="
      - ls -al
      - echo "==============================================="