version: 0.2

env:
  variables:
    ENVIRONMENT_TERRAFORM_IAM_ROLE_ARN: 'arn:aws:iam::723123699647:role/terraform'
    cluster_arn: 'arn:aws:ecs:eu-west-2:723123699647:cluster/dlc-dev-spgw-ecs-cluster'
    service_name: 'dlc-dev-spgw-alfproxy'
    environment_name: 'delius-core-dev'
    PROJECT_NAME: 'hmpps-po-alfresco-proxy'
phases:
  pre_build:
    commands:
      - rm -rf terraform/env_configs
      - git clone https://github.com/ministryofjustice/hmpps-env-configs.git terraform/env_configs
      - ${CODEBUILD_SRC_DIR}/scripts/${STACK_PRE_BUILD_COMMANDS}
      - source ${CODEBUILD_SRC_DIR}/scripts/export-alfresco-proxy-version.sh
      - echo "-------------------------- PRE-BUILD --------------------------"
      - echo "Value of environment var TF_VAR_image_version=${TF_VAR_image_version}"
      - echo "----------------------------------------------------------"
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}/terraform
      - export CUSTOM_COMMON_PROPERTIES_DIR=${CODEBUILD_SRC_DIR}/terraform/env_configs/common
      - cd ${CODEBUILD_SRC_DIR}/terraform/components
      - echo ""
      - echo ""
      - echo ""
      - echo "-------------------------- BUILD --------------------------"
      - echo "Value of environment var TF_VAR_image_version=${TF_VAR_image_version}"
      - echo "----------------------------------------------------------"
      - ${CODEBUILD_SRC_DIR}/scripts/1-stack-plan.sh
      - ${CODEBUILD_SRC_DIR}/scripts/2-stack-apply.sh
  post_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/${STACK_POST_BUILD_COMMANDS}
artifacts:
  files:
    - '**/*'
  name: $Env:PROJECT_NAME-$(date +%Y-%m-%d-%H-%m-%S)