version: 0.2

env:
  variables:
    service_name: 'dlc-dev-spgw-alfproxy'
    cluster_arn: 'arn:aws:ecs:eu-west-2:723123699647:cluster/dlc-dev-spgw-alfproxy'
    terraform_role_arn: 'arn:aws:iam::723123699647:role/terraform'
    desired_count: '1'
    deployment_timeout: '36000'
    IMAGE_REGISTRY: '895523100917.dkr.ecr.eu-west-2.amazonaws.com'
    IMAGE_NAME: 'hmpps/spgw-alfresco-proxy'
phases:
  pre_build:
    commands:
      - REPOSITORY_URI=${IMAGE_REGISTRY}/${IMAGE_NAME}
      - echo "-----------------------------------------------"
      - cat ${CODEBUILD_SRC_DIR}/image.json
      - echo "==============================================="
      - image_tag=`cat ${CODEBUILD_SRC_DIR}/image.json | jq -r '.tag'`
      - docker_image=${REPOSITORY_URI}:${image_tag}
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/run-ecs-deploy.sh