version: 0.2

env:
  variables:
    APPLICATION_NAME: 'hmpps-delius-po-alfresco-proxy'
    SPG_ALFRESCO_HEALTH_ENDPOINT: '/alfresco/service/noms-spg/notificationStatus'
    SPG_ALFRESCO_BASE_URL: ''
phases:
  pre_build:
    commands:
      - gradle build --dry-run --configure-on-demand --daemon
  build:
    commands:
      - gradle clean test cucumber
reports:
  UnitTestReports:
    files:
      - '**/*'
    base-directory: 'build/test-results'
    file-format: 'JunitXml'
  IntegrationTestReports:
    files:
      - 'cucumber.json'
    base-directory: 'build/cucumber'
    file-format: 'CucumberJson'