version: 0.2

env:
  variables:
    APPLICATION_NAME: 'SPG PO Alfresco Proxy'
    SPG_ALFRESCO_HEALTH_ENDPOINT: '/alfresco/service/noms-spg/notificationStatus'
    SPG_ALFRESCO_BASE_URL: ''
    test_results_bucket: 'tf-eu-west-2-hmpps-eng-dev-ci-test-results-s3bucket'
    project_name: 'hmpps-po-alfresco-proxy'
    PROJECT_NAME: 'hmpps-po-alfresco-proxy'
phases:
  install:
    commands:
      - apt update
      - apt install jq
      - apt install awscli
  pre_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/repo-details.sh
      - gradle build --dry-run --configure-on-demand --daemon
  build:
    commands:
      - gradle clean test cucumber bootJar
  post_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/archive-application-test-artifacts.sh
reports:
  UnitTestReports:
    files:
      - '**/*'
    base-directory: 'build/test-results'
    file-format: 'JunitXml'
  IntegrationTestReports:
    files:
      - 'cucumber.json'
    base-directory: 'build/cucumber'
    file-format: 'CucumberJson'
artifacts:
  files:
    - '**/*'
  name: $Env:PROJECT_NAME-$(date +%Y-%m-%d-%H-%m-%S)