version: 0.2

env:
  variables:
    APPLICATION_NAME: 'SPG PO Alfresco Proxy'
    SPG_ALFRESCO_HEALTH_ENDPOINT: '/alfresco/service/noms-spg/notificationStatus'
    SPG_ALFRESCO_BASE_URL: ''
    PROJECT_NAME: 'hmpps-po-alfresco-proxy'
phases:
  pre_build:
    commands:
      - echo "==============================================="
      - ls -al
      - echo "==============================================="
      - gradle build --dry-run --configure-on-demand --daemon
  build:
    commands:
      - gradle clean test cucumber bootJar
reports:
  UnitTestReports:
    files:
      - '**/*'
    base-directory: 'build/test-results'
    file-format: 'JunitXml'
  IntegrationTestReports:
    files:
      - 'cucumber.json'
    base-directory: 'build/cucumber'
    file-format: 'CucumberJson'
artifacts:
  files:
    - '**/*'
  name: $Env:PROJECT_NAME-$(date +%Y-%m-%d-%H-%m-%S)