version: 0.2

env:
  variables:
    ENVIRONMENT_TERRAFORM_IAM_ROLE_ARN: 'arn:aws:iam::723123699647:role/terraform'
    cluster_arn: 'arn:aws:ecs:eu-west-2:723123699647:cluster/dlc-dev-spgw-ecs-cluster'
    service_name: 'dlc-dev-spgw-alfproxy'
    environment_name: 'delius-core-dev'
    TF_VAR_docker_image: 'hub.docker.com/r/rodolpheche/wiremock'
    TF_VAR_image_version: '2.26.3-alpine'
    TF_VAR_internal_health_endpoint: 'http://localhost:8080/__admin/mappings'
phases:
  pre_build:
    commands:
      - rm -rf terraform/env_configs
      - git clone https://github.com/ministryofjustice/hmpps-env-configs.git terraform/env_configs
      - ${CODEBUILD_SRC_DIR}/scripts/terminate-instances.sh
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}/terraform
      - export CUSTOM_COMMON_PROPERTIES_DIR=${CODEBUILD_SRC_DIR}/terraform/env_configs/common
      - cd ${CODEBUILD_SRC_DIR}/terraform/components
      - ${CODEBUILD_SRC_DIR}/scripts/1-stack-plan.sh
      - ${CODEBUILD_SRC_DIR}/scripts/2-stack-apply.sh
  post_build:
    commands:
      - curl http://alfresco.dev.delius-core.probation.hmpps.dsd.io:8080/__admin/mappings