version: 0.2

env:
  variables:
    environment_name: 'delius-core-dev'
phases:
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}/terraform
      - export CUSTOM_COMMON_PROPERTIES_DIR=${CODEBUILD_SRC_DIR}/terraform/env_configs/common
      - cd ${CODEBUILD_SRC_DIR}/terraform/components
      - ${CODEBUILD_SRC_DIR}/scripts/1-stack-plan.sh
      - ${CODEBUILD_SRC_DIR}/scripts/2-stack-apply.sh