version: 0.2

env:
  variables:
    IMAGE_REGISTRY: '895523100917.dkr.ecr.eu-west-2.amazonaws.com'
    IMAGE_NAME: 'hmpps/spgw-alfresco-proxy'
    PROJECT_NAME: 'hmpps-po-alfresco-proxy'
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - aws sts get-caller-identity
      - eval $(aws --region ${AWS_REGION} ecr get-login --no-include-email)
      - aws sts get-caller-identity
      - REPOSITORY_URI=${IMAGE_REGISTRY}/${IMAGE_NAME}
      - echo "-----------------------------------------------"
      - cat ${CODEBUILD_SRC_DIR}/repo-details.json
      - echo "==============================================="
      - shortened_hash=`cat ${CODEBUILD_SRC_DIR}/repo-details.json | jq -r '.shortenedHash'`
      - TAG="dev-${shortened_hash}"
  build:
    commands:
      - echo Docker image build started on `date`
      - ${CODEBUILD_SRC_DIR}/scripts/build-docker-image.sh
  post_build:
    commands:
      - echo Docker image build completed on `date`
      - ${CODEBUILD_SRC_DIR}/scripts/upload-docker-image.sh
      - ${CODEBUILD_SRC_DIR}/scripts/image-details.sh
artifacts:
  files:
    - '**/*'
  name: $Env:PROJECT_NAME-$(date +%Y-%m-%d-%H-%m-%S)