version: 0.2

env:
  variables:
    environment_name: 'delius-core-dev'
    cluster_arn: 'arn:aws:ecs:eu-west-2:723123699647:cluster/dlc-dev-spgw-ecs-cluster'
    PROJECT_NAME: 'hmpps-po-alfresco-proxy'
phases:
  pre_build:
    commands:
      - echo "-------------------> dev-${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - rm -rf terraform/env_configs
      - git clone https://github.com/ministryofjustice/hmpps-env-configs.git terraform/env_configs
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}/terraform
      - export CUSTOM_COMMON_PROPERTIES_DIR=${CODEBUILD_SRC_DIR}/terraform/env_configs/common
      - cd ${CODEBUILD_SRC_DIR}/terraform/components
      - ${CODEBUILD_SRC_DIR}/scripts/1-stack-plan.sh
artifacts:
  files:
    - '**/*'
  name: $Env:PROJECT_NAME-$(date +%Y-%m-%d-%H-%m-%S)