version: 0.2

env:
  variables:
    AWS_REGION:  'eu-west-2'
    environment_name: 'delius-core-sandpit'
    ENV_CONFIGS_DIR: '${CODEBUILD_SRC_DIR}/env_configs'
    CUSTOM_COMMON_PROPERTIES_DIR: '${CODEBUILD_SRC_DIR}/env_configs/common'
phases:
  pre_build:
    commands:
      - rm -rf env_configs
      - git clone https://github.com/ministryofjustice/hmpps-env-configs.git env_configs
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/src/main/terraform
      - ${CODEBUILD_SRC_DIR}/stack-plan.sh