version: 0.2

env:
  variables:
    AWS_REGION:  'eu-west-2'
    environment_name: 'delius-core-sandpit'
phases:
  pre_build:
    commands:
      - rm -rf env_configs
      - git clone https://github.com/ministryofjustice/hmpps-env-configs.git env_configs
  build:
    commands:
      - export ENV_CONFIGS_DIR=${CODEBUILD_SRC_DIR}/env_configs
      - export CUSTOM_COMMON_PROPERTIES_DIR=${CODEBUILD_SRC_DIR}/env_configs/common
      - cd ${CODEBUILD_SRC_DIR}/src/main/terraform
      - ${CODEBUILD_SRC_DIR}/1-stack-plan.sh
      - ${CODEBUILD_SRC_DIR}/2-stack-apply.sh